### ISSUE TITLE
Privacy Settings - clarification what settings we offer and how to implement it technically

### ISSUE THREAD

**Issue by ZihRah** [trufi-association/hamburg-bike-app#27]

**Comment by ValorNaram** [comment]
Preparational paper:

# What data we send and where

## Declaration of services

**OSM Reverse Geocoding Service Nominatim:**
It is being used to be able to convert e.g.: "Eiscafe Venezia" (what the user types in) to a location like (53.457584, 10.447745).

**Map Tile Provider CartoDB**
It is being used to display the background map to the user.

**Backend (Routing Engine OTP2)**
It is our OTP2 instance used to provide routing capabilities to the app.
We are in full control of that service

## Where we send/receive data from

**Backend (Routing Engine OTP2):**
Receives everything what Frontend sends

**Frontend:**
  - OSM Reverse Geocoding Service Nominatim
  - Map Tile Provider CartoDB
  - Backend (Routing Engine OTP2)

## What kind of data we send

**To all services we send the following personal data:**
  - IP address
  - Resource url (what kind of data we ask for)
  - Timestamp of request (generated at server side)
  - total amount of requests made (generated at server side, only services with a quota do that)

**Frontend:**
  - ***OSM Reverse Geocoding Service Nominatim***
    - Resource url containing the following:
      - what the user typed in the search bar
      - current location or approx. one or not at all depending on user settings (did the user allowed the app access to his current location, or did the user grant the permission to send the current location to that server (an in-app setting we can create)
  - ***Map Tile Provider CartoDB***
    - Resource url containing the following:
      - computed address of a map tile (an image square)
  - ***Backend (Routing Engine OTP2)***
    - Resource url containing the following:
      - the coordinates of the start location
      - the coordinates of the end location
      - user specified routing options (if our app provides that possibility, otherwise routing options are hardcoded by app and therefore identical for all app users)

# Privacy Adjustment

My recommendations (Sören Reinecke) to proper adjustment to comply with GDPR are:

**Frontend**
The frontend (the "Bike App Hamburg") must provide an option to the user that the user can opt out from sending their current location to the service "OSM Reverse Geocoding Service Nominatim". This can be done by displaying the following to the user on a privacy settings screen;

- [ ] Don't include my current location in the request to the service "OSM Reverse Geocoding Service Nominatim"
  The service allows you to search for e.g. "Eiscafè Venezia" and returns search results allowing to choose a "Eiscafé Venezia" result you want a route to. In order to show you the entries near you and not in Schleswig-Holstein when you're in Hamburg the service "OSM Reverse Geocoding Service Nominatim" needs your current location. If you don't want this app to include your current location to the request to that service then tick that box and this app will respect your choice for future requests.

Also the first time the user uses our app they need to be prompted to accept our privacy policy.

**Comment by ValorNaram** [comment]
**Please comment on this** because I AM NOT THERE IN THE NEXT MEETING . Also a Sören needs at least one week vacation.
